# Generated by Django 5.0.7 on 2025-05-02 07:01

import app1.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutOffPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_time', models.TimeField(default=app1.models.CutOffPolicy.get_default_cutoff_time)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_policy', to='app1.student')),
            ],
        ),
    ]
