# Generated by Django 5.0.7 on 2025-05-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_cutoffpolicy_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffpolicy',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_policy', to='app1.student'),
        ),
    ]
